stages:
    - test
    - publish

publish_github:
    stage: publish
    tags:
        - shell
    script:
        - git remote rm github || true;
        - git remote add github https://${GITHUB_REPO_TOKEN}@github.com/mxcd/gitlab-x
        - git push github master
    only:
        - master